
import __ASTRO_IMAGE_IMPORT_2q0P2m from "../../assets/grounded_images/blog_01_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F01-traditional-8-course-wedding-menu.md";
import __ASTRO_IMAGE_IMPORT_rET7C from "../../assets/grounded_images/blog_02_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F02-wedding-catering-budget-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1DBHmn from "../../assets/grounded_images/blog_03_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F03-food-tasting.md";
import __ASTRO_IMAGE_IMPORT_Z263mij from "../../assets/grounded_images/blog_04_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F04-hygiene-and-temperature-control.md";
import __ASTRO_IMAGE_IMPORT_28c9Oa from "../../assets/grounded_images/blog_05_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-corporate-private-catering.md";
import __ASTRO_IMAGE_IMPORT_Z2kDfyR from "../../assets/grounded_images/blog_06_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F06-signature-dishes.md";
import __ASTRO_IMAGE_IMPORT_Z1RwWVY from "../../assets/grounded_images/blog_07_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F07-housewarming-catering-setup.md";
import __ASTRO_IMAGE_IMPORT_112mpf from "../../assets/grounded_images/blog_08_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F08-waitstaff-service-flow.md";
import __ASTRO_IMAGE_IMPORT_Z2vVI2e from "../../assets/grounded_images/blog_09_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F09-outdoor-tent-infrastructure.md";
import __ASTRO_IMAGE_IMPORT_2wAWst from "../../assets/grounded_images/blog_10_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F10-60-years-chef-experience.md";
import __ASTRO_IMAGE_IMPORT_19eAzP from "../../assets/grounded_images/blog_11_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F11-choosing-packages.md";
import __ASTRO_IMAGE_IMPORT_Z1sp4fK from "../../assets/grounded_images/blog_12_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F12-catering-industry-trends.md";
export default new Map([["../../assets/grounded_images/blog_01_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F01-traditional-8-course-wedding-menu.md", __ASTRO_IMAGE_IMPORT_2q0P2m], ["../../assets/grounded_images/blog_02_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F02-wedding-catering-budget-guide.md", __ASTRO_IMAGE_IMPORT_rET7C], ["../../assets/grounded_images/blog_03_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F03-food-tasting.md", __ASTRO_IMAGE_IMPORT_Z1DBHmn], ["../../assets/grounded_images/blog_04_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F04-hygiene-and-temperature-control.md", __ASTRO_IMAGE_IMPORT_Z263mij], ["../../assets/grounded_images/blog_05_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F05-corporate-private-catering.md", __ASTRO_IMAGE_IMPORT_28c9Oa], ["../../assets/grounded_images/blog_06_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F06-signature-dishes.md", __ASTRO_IMAGE_IMPORT_Z2kDfyR], ["../../assets/grounded_images/blog_07_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F07-housewarming-catering-setup.md", __ASTRO_IMAGE_IMPORT_Z1RwWVY], ["../../assets/grounded_images/blog_08_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F08-waitstaff-service-flow.md", __ASTRO_IMAGE_IMPORT_112mpf], ["../../assets/grounded_images/blog_09_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F09-outdoor-tent-infrastructure.md", __ASTRO_IMAGE_IMPORT_Z2vVI2e], ["../../assets/grounded_images/blog_10_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F10-60-years-chef-experience.md", __ASTRO_IMAGE_IMPORT_2wAWst], ["../../assets/grounded_images/blog_11_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F11-choosing-packages.md", __ASTRO_IMAGE_IMPORT_19eAzP], ["../../assets/grounded_images/blog_12_cover_khmer.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F12-catering-industry-trends.md", __ASTRO_IMAGE_IMPORT_Z1sp4fK]]);
		